apiVersion: skaffold/v3
kind: Config
metadata:
  name: data-info
build:
  artifacts:
    - image: harbor.cyverse.org/de/data-info
  tagPolicy:
    gitCommit: {}
  local: {}
  platforms:
    - "linux/amd64"
manifests:
  rawYaml:
    - k8s/data-info.yml
deploy:
  kubectl: {}
