apiVersion: skaffold/v1
kind: Config
metadata:
  name: data-info
deploy:
  kubectl:
    manifests:
    - k8s/data-info.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/data-info
  local: {}
